"""add_budget_and_labor_cost_tables

Revision ID: 0c579288c385
Revises: c4d5e6f7a8b9
Create Date: 2026-06-30 09:40:23.662021
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c579288c385'
down_revision: Union[str, None] = 'c4d5e6f7a8b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hardware_name'), 'hardware', ['name'], unique=True)
    op.create_table('labor_costs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('cost_per_m2', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labor_costs_job_type'), 'labor_costs', ['job_type'], unique=True)
    op.create_table('budgets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('aluminum_series_id', sa.String(length=36), nullable=True),
    sa.Column('finish_id', sa.String(length=36), nullable=True),
    sa.Column('glass_type_id', sa.String(length=36), nullable=True),
    sa.Column('height_m', sa.Float(), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=False),
    sa.Column('material_cost', sa.Float(), nullable=False),
    sa.Column('labor_cost', sa.Float(), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('discount_pct', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['aluminum_series_id'], ['aluminum_series.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['finish_id'], ['finishes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['glass_type_id'], ['glass_types.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budgets_project_id'), 'budgets', ['project_id'], unique=False)
    op.create_table('budget_hardware',
    sa.Column('budget_id', sa.String(length=36), nullable=False),
    sa.Column('hardware_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['budget_id'], ['budgets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hardware_id'], ['hardware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('budget_id', 'hardware_id')
    )
    op.drop_index('ix_hardware_items_name', table_name='hardware_items')
    op.drop_table('hardware_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hardware_items',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='hardware_items_pkey')
    )
    op.create_index('ix_hardware_items_name', 'hardware_items', ['name'], unique=True)
    op.drop_table('budget_hardware')
    op.drop_index(op.f('ix_budgets_project_id'), table_name='budgets')
    op.drop_table('budgets')
    op.drop_index(op.f('ix_labor_costs_job_type'), table_name='labor_costs')
    op.drop_table('labor_costs')
    op.drop_index(op.f('ix_hardware_name'), table_name='hardware')
    op.drop_table('hardware')
    # ### end Alembic commands ###
