"""add_signature_and_evidence_tables

Revision ID: e5f6a7b8c9d0
Revises: 0c579288c385
Create Date: 2026-07-02 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e5f6a7b8c9d0"
down_revision: Union[str, None] = "0c579288c385"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "signatures",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("budget_version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("signer_name", sa.String(length=255), nullable=True),
        sa.Column("signer_email", sa.String(length=255), nullable=True),
        sa.Column("signer_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("signature_image", sa.Text(), nullable=True),
        sa.Column("pdf_hash", sa.String(length=64), nullable=True),
        sa.Column("signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "pending", "signed", "rejected",
                name="signaturestatus",
                create_type=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signatures_project_id"), "signatures", ["project_id"], unique=False
    )

    op.create_table(
        "signature_evidence",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("signature_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_type", sa.String(length=50), nullable=False),
        sa.Column("evidence_value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["signature_id"],
            ["signatures.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_signature_evidence_signature_id"),
        "signature_evidence",
        ["signature_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signature_evidence_evidence_type"),
        "signature_evidence",
        ["evidence_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_signature_evidence_evidence_type"),
        table_name="signature_evidence",
    )
    op.drop_index(
        op.f("ix_signature_evidence_signature_id"),
        table_name="signature_evidence",
    )
    op.drop_table("signature_evidence")
    op.drop_index(
        op.f("ix_signatures_project_id"),
        table_name="signatures",
    )
    op.drop_table("signatures")
    # Drop enum type
    op.execute("DROP TYPE IF EXISTS signaturestatus")
    # ### end Alembic commands ###
